### ISSUE TITLE
500

### ISSUE THREAD

**Issue by elvis-ZJ** [hafizjavaid/Nuxt3-AI-Sass#1]
500
supabaseUrl is required.

I Missing .env，SUPABASE_URL &  SUPABASE_KEY，Where to get its.

**Comment by hafizjavaid** [comment]
Hi @elvis-ZJ 

Please watch the video from here

https://youtu.be/UPxId0g4QyI?si=vGtHaVmJdla_3AcG&t=1268

I'm explaining how we can set the supabase configurations
